export const TOURNAMENT_FETCH_START = 'TOURNAMENT_FETCH_START'
export const TOURNAMENT_FETCH_END = 'TOURNAMENT_FETCH_END'
export const TOURNAMENT_FETCH_ERROR = 'TOURNAMENT_FETCH_ERROR'
export const TOURNAMENT_CHECK = 'TOURNAMENT_CHECK'

export const STATS_FETCH_START = 'STATS_FETCH_START'
export const STATS_FETCH_ERROR = 'STATS_FETCH_ERROR'
export const STATS_FETCH_END = 'STATS_FETCH_END'
